# Meta Data for SEO

## Homepage
title = "Eventuous"
titleSeparator = "-"
titleAddition = "Event Sourcing for .NET"
description = "Opinionated and volatile library with building blocks for production-grade event-sourced applications"

## Open Graph + Twitter Cards
images = ["e-logo.png"]
#twitterSite = "henkverlinde"
twitterCreator = "Zimareff"
#facebookAuthor = "verlinde.henk"
#facebookPublisher = "verlinde.henk"
ogLocale = "en_GB"

## JSON-LD
schemaType = "Organization"
schemaLogo = "e-logo.png"
#schemaTwitter = "https://twitter.com/henkverlinde"
schemaGitHub = "https://github.com/Eventuous/eventuous"
schemaSection = "blog"

## Sitelinks Search Box
siteLinksSearchBox = false

## Chrome Browser
themeColor = "#fff"

# Images
quality = 85
bgColor = "#fff"
landscapePhotoWidths = [900, 800, 700, 600, 500]
portraitPhotoWidths = [800, 700, 600, 500]
lqipWidth = "20x"

# Footer
footer = "Copyright © 2021 Eventuous - <a href='https://ubiquitous.no'>Ubiquitous AS</a> - <a href='https://zimarev.com'>Alexey Zimarev</a>"

# Alert
alert = true
alertText = "Like Eventuous? <a class=\"alert-link\" href=\"https://github.com/Eventuous/eventuous\">Sponsor us  on GitHub</a>. Thanks!</a>"

# Edit Page
docsRepo = "https://github.com/Eventuous/docs"
editPage = true

[options]
  lazySizes = true
  clipBoard = true
  instantPage = false
  flexSearch = true
  darkMode = true
  bootStrapJs = false
  breadCrumb = false
